# Generated by Django 3.1.4 on 2024-09-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_auto_20240928_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='drive_link',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
