version: '3'
services:
  django-app:
    image: django-app:${TAG}   # This will be dynamically updated by the GitHub Actions workflow
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
