name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Updated to v2

    - name: Login to DockerHub
      uses: docker/login-action@v2  # Updated to v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3  # Updated to v3
      with:
        context: .
        push: true
        tags: arunbabu101/edureka:${{ github.sha }}  # Use your actual image name

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6  # Ensure this is the latest version
      with:
        host: "YOUR_EC2_PUBLIC_IP"  # Replace with your EC2 instance's public IP
        username: "ubuntu"
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Stop and remove containers using port 8000
          containers=$(docker ps -q --filter publish=8000)
          if [ ! -z "$containers" ]; then
            docker stop $containers
            docker rm $containers
          fi
          
          # Pull the new image
          docker pull arunbabu101/edureka:${{ github.sha }}  # Use your actual image name
          
          # Stop and remove the edureka container if it exists
          if docker ps -a --format '{{.Names}}' | grep -q '^edureka$'; then
            docker stop edureka
            docker rm edureka
          fi

          # Run the new container
          docker run -d --name edureka -p 8000:8000 arunbabu101/edureka:${{ github.sha }}  # Use your actual image name
          
          # Clean up unused Docker resources
          docker system prune -af
