name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

    steps:
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          python manage.py migrate
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push Docker image
      - name: Build and Push Docker image
        run: |
          # Build the Docker image with the date tag
          DATE_TAG=$(date +'%Y%m%d')  # Set the date format as needed
          docker build -t arunbabu101/edureka:$DATE_TAG .

          # Push the Docker image with the date tag
          docker push arunbabu101/edureka:$DATE_TAG

      # Deploy to AWS EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.42.127 << EOF
            docker pull arunbabu101/edureka:$DATE_TAG
            docker stop $(docker ps -q --filter ancestor=arunbabu101/edureka:$DATE_TAG)
            docker run -d -p 8000:8000 arunbabu101/edureka:$DATE_TAG
          EOF
