name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: arunbabu101/edureka:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: "YOUR_EC2_PUBLIC_IP"  # Replace with your EC2 public IP
          username: "ubuntu"
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Stop and remove containers using port 8000
            containers=$(docker ps -q --filter publish=8000)
            if [ ! -z "$containers" ]; then
              docker stop $containers
              docker rm $containers
            fi
            
            # Pull the new image
            docker pull arunbabu101/edureka:${{ github.sha }}
            
            # Stop and remove the edureka container if it exists
            if docker ps -a --format '{{.Names}}' | grep -q '^edureka$'; then
              docker stop edureka
              docker rm edureka
            fi

            # Run the new container
            docker run -d --name edureka -p 8000:8000 arunbabu101/edureka:${{ github.sha }}
            
            # Clean up unused Docker resources
            docker system prune -af
