name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Docker Hub using credentials stored as GitHub secret
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push the Docker image to Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: arunbabu101/edureka:${{ github.sha }}

    # Step 5: Deploy to EC2 via SSH and pull the new Docker image
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}   # EC2 public IP address stored in GitHub secrets
        username: "ubuntu"
        key: ${{ secrets.EC2_SSH_KEY }}     # SSH private key for EC2 access stored in GitHub secrets
        script: |
          # Stop and remove any running containers using port 8000
          containers=$(docker ps -q --filter publish=8000)
          if [ -n "$containers" ]; then
            docker stop $containers
            docker rm $containers
          fi

          # Pull the new image from Docker Hub
          docker pull arunbabu101/edureka:${{ github.sha }}

          # Stop and remove the existing 'edureka' container if it exists
          if docker ps -a --format '{{.Names}}' | grep -q '^edureka$'; then
            docker stop edureka
            docker rm edureka
          fi

          # Run the new container on port 8000
          docker run -d --name edureka -p 8000:8000 arunbabu101/edureka:${{ github.sha }}

          # Clean up unused Docker resources to save spaces
          docker system prune -af
